### ISSUE TITLE
About 1000==1 GPU

### ISSUE THREAD

**Issue by hjiema** [hkust-adsl/kubernetes-scheduler-simulator#13]
Hello! First and foremost, I would like to express my sincere gratitude for your hard work on the Kubernetes Scheduler Simulator project. Your contribution is of immense value to the community.

During my reading of the documentation and usage, I came across a question regarding the GPU metrics. I noticed that `1000==1 GPU` is used as an important criterion in certain configurations. I am curious about the meaning behind this metric and why such a division was chosen. I would greatly appreciate it if you could provide some background information or explanation on this matter.

Thank you once again for your contribution, and I look forward to your response.

Best regards!

**Comment by qzweng** [comment]
Hi @hjiema ,

The idea of 1000 milliGPU =1 GPU is inspired by the Kubernetes CPU units ([docs](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units)):

> ## CPU units
> The CPU resource is measured in CPU units. One CPU, in Kubernetes, is equivalent to:
> - 1 AWS vCPU
> - 1 GCP Core
> - 1 Azure vCore
> - 1 Hyperthread on a bare-metal Intel processor with Hyperthreading
>
> Fractional values are allowed. A Container that requests 0.5 CPU is guaranteed half as much CPU as a Container that requests 1 CPU. You can use the suffix m to mean milli. For example 100m CPU, 100 milliCPU, and 0.1 CPU are all the same. Precision finer than 1m is not allowed.

Since the simulator is featured by the support of GPU sharing workloads, it allows GPU requirements with precision between 1 GPU and 1/1000 GPUs.
